### PR TITLE
Code to obtain required data

### PR DESCRIPTION
**Pull request by cnascim1**
-code to obtain required data from 2024-07-15 (same data given until this data in other ticket)
-table with samples given in helpdesk 
-output

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @cnascim1)

___
*[`EBH-2633/msi_tmb_tso500.py` line 64 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kk1tX7rZzNqLRWqBF:-O-kk1tX7rZzNqLRWqBG:b7cu1dw) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L64)):*
> ```Python
>     #and remove /output/ from the beginning of the string to just get the
>     #name of the single folder, rather than path
>     folder_name = [
> ```

youre always checking for the first folder_name in your list. Can you check that there isnt another folder_name? If the length of folder_name exceeds 1, then there are two runs worth in your project. This might need to be noted
___
*[`EBH-2633/msi_tmb_tso500.py` line 183 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kkGLUBkuju3CBa6PQ:-O-kkGLUBkuju3CBa6PR:b-j4z9fq) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L183)):*
> ```Python
>         )
>         #Get indexes of section of TSV we want
>         start_string = 'DNA Sample ID'
> ```

why not start at row where TMB is?
___
*[`EBH-2633/msi_tmb_tso500.py` line 192 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kl07416CWkNjtd1rp:-O-kl07416CWkNjtd1rq:b3mf55k) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L192)):*
> ```Python
>         #Change column names to the Metric and value associated
>         msi_tmb.columns = ['Metric', 'Value']
>         #msi_tmb.reset_index(drop=True, inplace=True)
> ```

remove commented out code
___
*[`EBH-2633/msi_tmb_tso500.py` line 282 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kkQIe1gEER6LJJcCI:-O-kkQIe1gEER6LJJcCJ:b-54dpbc) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L282)):*
> ```Python
>     #drop duplicates from transposing - keep first to act as column
>     all_samples_gene_df = all_samples_gene_df.drop_duplicates(keep='first')
>     #get rid of metrics that are not important
> ```

can you comment what these metrics are? or the columns you are dropping?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @cnascim1)

___
*[`EBH-2633/msi_tmb_tso500.py` line 294 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-klSTR8yLZV4yLS80D:-O-klSTR8yLZV4yLS80E:bviug0a) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L294)):*
> ```Python
> 
> 
> #Get final matches between helpdesk samples and all obtained
> ```

can you move this chunk above in main?

**Review by cnascim1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`EBH-2633/msi_tmb_tso500.py` line 64 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kk1tX7rZzNqLRWqBF:-O-pXlFb0h9yUihifpvP:b-7rl0kd) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L64)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

youre always checking for the first folder_name in your list. Can you check that there isnt another folder_name? If the length of folder_name exceeds 1, then there are two runs worth in your project. This might need to be noted
</blockquote></details>

done
___
*[`EBH-2633/msi_tmb_tso500.py` line 183 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kkGLUBkuju3CBa6PQ:-O-pXPwM8yg6b5qrDUcN:b-gvo8wp) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L183)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

why not start at row where TMB is?
</blockquote></details>

This way I could get the run ID and sample ID in an easier way. Adding both as extra columns was causing issues when transposing if we want one sample per lane
___
*[`EBH-2633/msi_tmb_tso500.py` line 192 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kl07416CWkNjtd1rp:-O-pXi2d8xc-7SmkuREV:bb7f2mf) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L192)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

remove commented out code
</blockquote></details>

done
___
*[`EBH-2633/msi_tmb_tso500.py` line 282 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-kkQIe1gEER6LJJcCI:-O-pXqtu6_3Aj4vQ5dqk:bb7f2mf) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L282)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can you comment what these metrics are? or the columns you are dropping?
</blockquote></details>

done
___
*[`EBH-2633/msi_tmb_tso500.py` line 294 at r2](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-klSTR8yLZV4yLS80D:-O-pXsAc3RE25DoW2ev6:bb7f2mf) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/5254fae525e50a881d352f1d024b842f3ae557af/EBH-2633/msi_tmb_tso500.py#L294)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can you move this chunk above in main?
</blockquote></details>

done

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @cnascim1)

___
*[`EBH-2633/msi_tmb_tso500.py` line 61 at r3](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1#-O-q11mn-mVgD3WomN7z:-O-q11mo3HL0dKSTpbHB:bsnflju) ([raw file](https://github.com/eastgenomics/solid_cancer_service/blob/39383c9570899cf5ac82c535701dfed7c3ab14d3/EBH-2633/msi_tmb_tso500.py#L61)):*
> ```Python
>     )
>      #Check if there is only one run in the project 
>     if len(folder_names) > 1:
> ```

would suggest if length is > 1, check the subdirecotry has a folder named "TSO500_reports_workflow" and choose that name ?

**Review by Aisha-D — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: all files reviewed, 1 unresolved discussion (waiting on @cnascim1)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/solid_cancer_service/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cnascim1)

**Pull request merged**
